[2023-09-04T17:57:42.323+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_upload.upload_to_s3_rapid manual__2023-09-04T17:57:41.311038+00:00 [queued]>
[2023-09-04T17:57:42.336+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_upload.upload_to_s3_rapid manual__2023-09-04T17:57:41.311038+00:00 [queued]>
[2023-09-04T17:57:42.337+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-04T17:57:42.353+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_s3_rapid> on 2023-09-04 17:57:41.311038+00:00
[2023-09-04T17:57:42.357+0000] {standard_task_runner.py:57} INFO - Started process 823 to run task
[2023-09-04T17:57:42.365+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 's3_upload', 'upload_to_s3_rapid', 'manual__2023-09-04T17:57:41.311038+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/s3_upload.py', '--cfg-path', '/tmp/tmpyf2x_dga']
[2023-09-04T17:57:42.368+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask upload_to_s3_rapid
[2023-09-04T17:57:42.431+0000] {task_command.py:415} INFO - Running <TaskInstance: s3_upload.upload_to_s3_rapid manual__2023-09-04T17:57:41.311038+00:00 [running]> on host 0f3e7eb4507c
[2023-09-04T17:57:42.508+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_upload' AIRFLOW_CTX_TASK_ID='upload_to_s3_rapid' AIRFLOW_CTX_EXECUTION_DATE='2023-09-04T17:57:41.311038+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-04T17:57:41.311038+00:00'
[2023-09-04T17:57:42.518+0000] {base.py:73} INFO - Using connection ID 's3_conn' for task execution.
[2023-09-04T17:57:42.519+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from login and password.
[2023-09-04T17:57:45.960+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/s3_upload.py", line 23, in upload_to_s3
    hook.load_file(filename=filename, key=key, bucket_name=bucket_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 138, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 92, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1058, in load_file
    if not replace and self.check_for_key(key, bucket_name):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 138, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 92, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 901, in check_for_key
    obj = self.head_object(key, bucket_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 138, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 92, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 886, in head_object
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 881, in head_object
    return self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
[2023-09-04T17:57:45.987+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=s3_upload, task_id=upload_to_s3_rapid, execution_date=20230904T175741, start_date=20230904T175742, end_date=20230904T175745
[2023-09-04T17:57:46.003+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 40 for task upload_to_s3_rapid (An error occurred (403) when calling the HeadObject operation: Forbidden; 823)
[2023-09-04T17:57:46.058+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T17:57:46.071+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
