[2023-09-04T19:26:34.667+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_upload_xcom.upload_to_s3_monthly manual__2023-09-04T19:26:32.373106+00:00 [queued]>
[2023-09-04T19:26:34.671+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_upload_xcom.upload_to_s3_monthly manual__2023-09-04T19:26:32.373106+00:00 [queued]>
[2023-09-04T19:26:34.671+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-04T19:26:34.677+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_s3_monthly> on 2023-09-04 19:26:32.373106+00:00
[2023-09-04T19:26:34.680+0000] {standard_task_runner.py:57} INFO - Started process 135 to run task
[2023-09-04T19:26:34.683+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 's3_upload_xcom', 'upload_to_s3_monthly', 'manual__2023-09-04T19:26:32.373106+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/s3_upload_xcom.py', '--cfg-path', '/tmp/tmpgd69pmz_']
[2023-09-04T19:26:34.684+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask upload_to_s3_monthly
[2023-09-04T19:26:34.714+0000] {task_command.py:415} INFO - Running <TaskInstance: s3_upload_xcom.upload_to_s3_monthly manual__2023-09-04T19:26:32.373106+00:00 [running]> on host a4701647eeb7
[2023-09-04T19:26:34.755+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_upload_xcom' AIRFLOW_CTX_TASK_ID='upload_to_s3_monthly' AIRFLOW_CTX_EXECUTION_DATE='2023-09-04T19:26:32.373106+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-04T19:26:32.373106+00:00'
[2023-09-04T19:26:34.756+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/s3_upload_xcom.py", line 22, in upload_to_s3
    data = task_instance.xcom_pull(tasks_ids="task_get_monthly_games")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'tasks_ids'
[2023-09-04T19:26:34.763+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=s3_upload_xcom, task_id=upload_to_s3_monthly, execution_date=20230904T192632, start_date=20230904T192634, end_date=20230904T192634
[2023-09-04T19:26:34.769+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 54 for task upload_to_s3_monthly (xcom_pull() got an unexpected keyword argument 'tasks_ids'; 135)
[2023-09-04T19:26:34.774+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T19:26:34.785+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
