[2023-09-04T17:45:41.241+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_upload.upload_to_s3_blitz manual__2023-09-04T17:45:40.264230+00:00 [queued]>
[2023-09-04T17:45:41.251+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_upload.upload_to_s3_blitz manual__2023-09-04T17:45:40.264230+00:00 [queued]>
[2023-09-04T17:45:41.252+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-04T17:45:41.266+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_s3_blitz> on 2023-09-04 17:45:40.264230+00:00
[2023-09-04T17:45:41.272+0000] {standard_task_runner.py:57} INFO - Started process 716 to run task
[2023-09-04T17:45:41.279+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 's3_upload', 'upload_to_s3_blitz', 'manual__2023-09-04T17:45:40.264230+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/s3_upload.py', '--cfg-path', '/tmp/tmpzddhcfd6']
[2023-09-04T17:45:41.282+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask upload_to_s3_blitz
[2023-09-04T17:45:41.346+0000] {task_command.py:415} INFO - Running <TaskInstance: s3_upload.upload_to_s3_blitz manual__2023-09-04T17:45:40.264230+00:00 [running]> on host 0f3e7eb4507c
[2023-09-04T17:45:41.426+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_upload' AIRFLOW_CTX_TASK_ID='upload_to_s3_blitz' AIRFLOW_CTX_EXECUTION_DATE='2023-09-04T17:45:40.264230+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-04T17:45:40.264230+00:00'
[2023-09-04T17:45:41.434+0000] {base.py:73} INFO - Using connection ID 's3_conn' for task execution.
[2023-09-04T17:45:41.435+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from login and password.
[2023-09-04T17:45:44.989+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/s3_upload.py", line 23, in upload_to_s3
    hook.load_file(filename=filename, key=key, bucket_name=bucket_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 138, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 92, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1058, in load_file
    if not replace and self.check_for_key(key, bucket_name):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 138, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 92, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 901, in check_for_key
    obj = self.head_object(key, bucket_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 138, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 92, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 886, in head_object
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 881, in head_object
    return self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
[2023-09-04T17:45:45.008+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=s3_upload, task_id=upload_to_s3_blitz, execution_date=20230904T174540, start_date=20230904T174541, end_date=20230904T174545
[2023-09-04T17:45:45.022+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task upload_to_s3_blitz (An error occurred (403) when calling the HeadObject operation: Forbidden; 716)
[2023-09-04T17:45:45.043+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T17:45:45.059+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
